# mywebapp services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mywebapp1-workorder
  labels:
    app: mywebapp1-workorder
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: mywebapp1-workorder
---
apiVersion: extensions/v1beta1 #TODO: Migrate to apps/v1
kind: Deployment
metadata:
  name: mywebapp1-workorder-v1
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: mywebapp1-workorder
        version: v1
    spec:
      containers:
        - name: mywebapp1-workorder
          image: acrcopopreprod.azurecr.io/copo-workorder-service-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

  # mywebapp services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mywebapp1-common
  labels:
    app: mywebapp1-common
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: mywebapp1-common
---
apiVersion: extensions/v1beta1 #TODO: Migrate to apps/v1
kind: Deployment
metadata:
  name: mywebapp1-common-v1
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: mywebapp1-common
        version: v1
    spec:
      containers:
        - name: mywebapp1-common
          image: acrcopopreprod.azurecr.io/copo-common-service-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

# mywebapp services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mywebapp1-org
  labels:
    app: mywebapp1-org
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: mywebapp1-org
---
apiVersion: extensions/v1beta1 #TODO: Migrate to apps/v1
kind: Deployment
metadata:
  name: mywebapp1-org-v1
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: mywebapp1-org
        version: v1
    spec:
      containers:
        - name: mywebapp1-org
          image: acrcopopreprod.azurecr.io/copo-organization-service-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        
---

  # mywebapp services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mywebapp1-ui
  labels:
    app: mywebapp1-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: mywebapp1-ui
---
apiVersion: extensions/v1beta1 #TODO: Migrate to apps/v1
kind: Deployment
metadata:
  name: mywebapp1-ui-v1
spec:
  replicas: 3
  minReadySeconds: 10 # Wait 2 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1 # When updating never have more than one extra pod. If replicas = 2 then never 3 pods when updating
  template:
    metadata:
      labels:
        app: mywebapp1-ui
        version: v1
    spec:
      containers:
        - name: mywebapp1-ui
          image: acrcopopreprod.azurecr.io/copo-ui-service-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
